globalThis.facebookURL = "";
globalThis.PinterestURL = "";
globalThis.twitterURL = "";
globalThis.redditURL = "";
globalThis.siteUrl = 'http://www.lovelyhomerecipes.com';
globalThis.homepageTitle = 'love ly home recipes';
globalThis.homepageTagline = 'Simple, delicious homemade recipes for everyday cooking. Discover easy meals, quick dinners, and tasty snacks made with love to brighten your table.';
globalThis.email = 'contact@lovelyhomerecipes.com';
globalThis.copyright = '2025-2026 love ly home recipes. All rights reserved.';
